// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK8oUDspJUsdluT1ClHFCu39wJt3AHYoA',
    appId: '1:947697186275:web:ad1ada476a4c951347dcd6',
    messagingSenderId: '947697186275',
    projectId: 'notebook-c06be',
    authDomain: 'notebook-c06be.firebaseapp.com',
    storageBucket: 'notebook-c06be.firebasestorage.app',
    measurementId: 'G-XPSDD34CEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDjkk7gEL6CJVhU_abYvM0siQ5-XN1olk',
    appId: '1:947697186275:android:fbad5c2158cbd94947dcd6',
    messagingSenderId: '947697186275',
    projectId: 'notebook-c06be',
    storageBucket: 'notebook-c06be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_G4bDi3SzeeD1LuvYopNfujk7RnqNPs',
    appId: '1:947697186275:ios:83d1fea50c98582e47dcd6',
    messagingSenderId: '947697186275',
    projectId: 'notebook-c06be',
    storageBucket: 'notebook-c06be.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC_G4bDi3SzeeD1LuvYopNfujk7RnqNPs',
    appId: '1:947697186275:ios:83d1fea50c98582e47dcd6',
    messagingSenderId: '947697186275',
    projectId: 'notebook-c06be',
    storageBucket: 'notebook-c06be.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK8oUDspJUsdluT1ClHFCu39wJt3AHYoA',
    appId: '1:947697186275:web:410d6ec369be689b47dcd6',
    messagingSenderId: '947697186275',
    projectId: 'notebook-c06be',
    authDomain: 'notebook-c06be.firebaseapp.com',
    storageBucket: 'notebook-c06be.firebasestorage.app',
    measurementId: 'G-8BMDLQX6VP',
  );
}
